language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=1.3.7
  - DJANGO=1.4.5
  - DJANGO=1.5

install:
  - "pip install -q Django==$DJANGO --use-mirrors"
  - "pip install argparse"

script:
  - python runtests.py
  
notifications:
  email: false
