language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"

env:
  - DJANGO=1.3.7
  - DJANGO=1.4.5
  - DJANGO=1.5
  - DJANGO=https://github.com/django/django/tarball/master

exclude:
  - env: DJANGO=1.5
    python: "2.5"
  - env: DJANGO=https://github.com/django/django/tarball/master
    python: "2.5"

install:
  - "pip install -q Django==$DJANGO --use-mirrors"
  - "pip install argparse"
  - "pip install pep8"

before_script:
  - "pep8 --ignore=E501,W293 oauth2_consumer"

script:
  - python runtests.py
  
notifications:
  email: false
